---
- name: Converge
  hosts: node*
  become: true
  vars:
    molecule_is_test: true
    k3s_build_cluster: false
    k3s_server_manifests_templates:
      - "molecule/highavailability/templates/00-ns-monitoring.yml.j2"
  roles:
    - role: xanmanning.k3s
