---
- name: Converge
  hosts: all
  become: true
  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      vars:
        molecule_is_test: true
        k3s_install_hard_links: true
        k3s_release_version: stable
        # k3s_agent:
          # snapshotter: native
