---
- name: Prepare
  hosts: all
  tasks:
    - name: Ensure apt cache is updated
      ansible.builtin.apt:
        update_cache: true
      when: ansible_pkg_mgr == 'apt'

    - name: Ensure iptables is installed
      ansible.builtin.package:
        name: iptables
        state: present
      when: ansible_pkg_mgr != 'dnf'

    - name: Ensure iptables is installed
      ansible.builtin.dnf:
        name: iptables
        state: present
      when: ansible_pkg_mgr == 'dnf'
