---

- name: Converge
  hosts: node*
  become: true
  vars:
    molecule_is_test: true
    k3s_use_experimental: true
    k3s_etcd_datastore: true
    k3s_server:
      secrets-encryption: true
  pre_tasks:
    - name: Set each node to be a control node
      ansible.builtin.set_fact:
        k3s_control_node: true
  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
