---
- name: Converge
  hosts: all
  become: true
  vars:
    pyratlabs_issue_controller_dump: true
    k3s_server:
      snapshotter: native
    k3s_agent:
      snapshotter: native
  pre_tasks:
    - name: Ensure k3s_debug is set
      ansible.builtin.set_fact:
        k3s_debug: true
  roles:
    - xanmanning.k3s
