---

- name: Ensure docker is uninstalled using Zypper
  community.general.zypper:
    name: docker
    state: absent
  register: ensure_docker_uninstalled
  until: ensure_docker_uninstalled is succeeded
  retries: 3
  delay: 10
  become: "{{ k3s_become_for_uninstall | ternary(true, false, k3s_become_for_all) }}"
